### ISSUE TITLE
Protein densities are much better but ligand densities are worse.

### ISSUE THREAD

**Issue by alburse** [rsanchezgarc/deepEMhancer#11]
Hi

I enjoyed using your tool and I think it does a really good job for protein densities and especially for the lower resolution densities. However, I realized that it just makes all the other densities worse. Ligands, lipidic densities are either worse or completely gone in multiple various maps that we have tried. Is there a way to change the behavior of deepEMhancer so it would preserve those densities? Thanks.

Alpay

**Comment by rsanchezgarc** [comment]
Hi,

I am afraid that this is the expected behaviour. DeepEMhancer has been trained on available atomic models coming from cryo-EM and it turns out that they most of them don't model well ligands or PTMs. As a results, DeepEMhancer is not prepared to enhance those regions and indeed, it may even mask them out . We are planning a future version using a subset of cryo-EM maps/atomic models focused on lipids and other PTMs but we do not have a release date yet. 

I am sorry I cannot help you now


Ruben

**Comment by alburse** [comment]
I understand and it makes sense, however, ligand densities are immensely important for cryoEM studies. I do not know how much training data do you need but I think there is quite a bit of them released recently for ligands. Unfortunately, it is not the case for proper lipidic and PTM densities. Would there be an option to provide a mask or model (mask around ligand model) to save the densities in interest? Thank you for your answer and I am looking forward to the advancements in deepEMhancer.

**Comment by rsanchezgarc** [comment]
Hi,

I agree, ligand and PTMs are the next big thing for cryo-EM, yet we think we do not have enough data to treat them properly. 

With respect to masking the parts you want to focus on, it should be easy to do that with any cryo-EM package (e.g., scipion/xmipp operate_volume). We have also been working on a method for automatic combination of post-processed maps, so that the final map would retain the best of each. In that way, you could try to combine the DeepEMhancer map and let’s say your B-factor or localDeblur map. @EstrellaFG could tell you where to find the method and how to use it.

Nevertheless, if you still would like to have it, I could create a simple script (should be 10 lines) that takes your DeepEMhancer map and removes what is not in a binary mask

Ruben

**Comment by alburse** [comment]
Thanks Ruben, that would be great, I would like to try your script if it is not much trouble to create it for you. I again appreciate your program. @EstrellaFG's input is also very much appreciated. 

Alpay

**Comment by EstrellaFG** [comment]
Hi @alburse, as Ruben has indicated, I recently developed a method to combine different reecosntructions of the same structure or different post-processings of the same map. The method is in Xmipp development version (as the methods is more recent than the last production version of Xmipp) and you can easily used through Scipion v3. You have to previously adjust all the maps that you want to comibine using protocol "volume adjust" (this step is very important in order to have all the maps with comparable values) and then you can use protocol "volume consensus" using as input the adjusted maps. The output map will be a combination of the input maps keeping the best resolution information among the input for each region. There is a secondary output that consists on a colormap that indicates you in which regions your input maps are more similar or have more differences. 
Please contact me if you have any doubt about the use or functioning of the method at me.fernandez@cnb.csic.es
Hope it helps!

**Comment by alburse** [comment]
Thank you @EstrellaFG. I will give it a try. I was going to install the latest Scipion v3 and I guess it is time.
