### ISSUE TITLE
Predicting time to completion?

### ISSUE THREAD

**Issue by mcianfrocco** [rsanchezgarc/deepEMhancer#2]
Hello - 

I'm wondering if you can provide any advice on predicting the time to completion for DeepEMhancer?  

I was testing this on a reconstruction that was a combined, full map (300x300x300 pixels) vs. the associated half map. The completion time took 15 minutes on 4 GPUs for the full map, but ~1 hr 15 min. for the half map.  Do you have any ideas as to why it took much longer and how to predict? I suspect it has to do with the map normalization?

Thank you,
Mike

**Comment by rsanchezgarc** [comment]
Dear Mike,

I am afraid that I have not performed a time benchmarking for DeepEMhancer, so I have not a good general answer about it (I will include it into the TO DO tasks). Just to get a feeling, this morning  I have executed DeepEMHancer on two volumes, one of size 240x240 and another of size 300x300x300 (sampling 0.82 A/pixel), measuring running times of 8 and 18 minutes.

I can also tell you is that this is an O(N3) algorithm and thus, if the size of the protein (in Angstroms) doubles, the running time will multiply by 8. And I can also tell you that sometimes, using 4 GPUs is slower than 2 (due to bottlenecks such as disk IO), this is something that you can optimize monitoring GPU usage using nvidia-smi and disk usage using something like atop.

Regarding the running times you measured, I agree with you that normalization and noise levels affect  the running time, since “empty” regions do not need to be processed. However, 5x running time for volumes of the same size seems too much and there may be many reasons behind it. To give you a more accurate answer, I will need that you provide with the exact commands you ran and the STDOUT the program produced. And  I also want to ask you if the full volume was pre-processed in some way (e.g. masked) or if you used as input only one half map (we recommend to use both halfs with  -i and -i2).

Thank you!

Ruben

**Comment by mcianfrocco** [comment]
Thank you for your comments - I think I found the issue related to how I was passing the gpuids to the command line. I think it's working consistently now. I am also now using both halves, it wasn't clear to me that it should have been _both_ half maps, although I knew half maps were required. 

Thank you,
Mike
