### ISSUE TITLE
Alternative to determine the noise statistics of a map prior to sharpening with the Enhancer

### ISSUE THREAD

**Issue by DennisDannecker** [rsanchezgarc/deepEMhancer#30]
Hello,

for my particular map the normal, default normalization mode, mode 1 does not work. It is a filament with hollow interior and thus expected to probably raise issues.

Now the approach with Chimera Volume cropping is weird, not poorly documented for ChimeraX (if any) and freely speaking, I have no idea what of my map I should for calculating the noise statistics. A region consisting of only noise...well, how can I make sure that I have such a region, what about the size of this region?
I thought maybe ResMap would provide the required noise statistic, so far I could not find it in its output.
I wish to avoid to go to the normalization mode 2 since this is explicitly advised against it for maps where this is not necessary.

Are there any alternatives you can think of that could provide me the two values for my map?

Thank you very much for your help.

Cheers 
Dennis

**Comment by rsanchezgarc** [comment]
Hi Dennis,

I am sorry to hear that you are having issues using DeepEMhancer. The noise statistics are important to properly normalize the map, so that DeepEMhancer can distinguish what is noise and signal more easily. Having said that, the noise mean, at least with Relion, should be very close to 0. The standard deviation can vary, I have seen values as small as 0.0001 and others as large as 0.01, so it is important to determine it. It doesn't matter if the estimation is very accurate, but it should be in the ~ correct order of magnitude. To do so, you need to select a patch/crop of the map in which you can be sure that there is no protein, lipids or any other source of signal. My advice is to take a box that is midway between the protein surface and the end of the shell of noise. The larger the patch the better, but a small patch would also work. You can check that the statistics should be pretty similar for different sizes. If you want to feel even more comfortable, you can compute the statistics across multiple crops. 

About how to do it in ChimeraX, have you looked at https://github.com/rsanchezgarc/deepEMhancer/blob/master/deepEMhancer_tutorial_06_23.pdf page 8? It may not be straightforward, but it should take no more than 3 or four attempts before you get a sensible crop (I don't know if there is a visual way of doing it as there was in Chimera).
Alternatively, you can compute the noise statistics by opening the map as 2D slices (imageJ, Fiji), and selecting a box in the desired regions. In principle, the noise should behave similarly in each slice, so estimating it from 2D is also ok.
